// The world map that lights up as you solve groups.
// It only draws: the data (SVG paths and pin positions) comes from assets/map-data.json,
// which is generated by scripts/build-map.mjs.

const SVG_NS = "http://www.w3.org/2000/svg";

function el(name, attrs = {}, parent = null) {
  const node = document.createElementNS(SVG_NS, name);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  if (parent) parent.appendChild(node);
  return node;
}

export async function loadMapData(url = "assets/map-data.json") {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (e) {
    console.warn("Map data not available:", e.message);
    return null;
  }
}

// Marker shapes, drawn in screen pixels around (0, 0).
const SHAPES = {
  city: () => el("circle", { r: 4.5, class: "shape" }),
  peak: () => el("polygon", { points: "0,-6.5 6,4.5 -6,4.5", class: "shape" }),
  water: () => el("polygon", { points: "0,-6.5 6.5,0 0,6.5 -6.5,0", class: "shape" }),
  area: () => el("rect", { x: -4.5, y: -4.5, width: 9, height: 9, rx: 2, class: "shape" }),
  micro: () => el("circle", { r: 5, class: "shape micro" }),
};

const reducedMotion = () => window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);

export function createWorldMap(container, data) {
  const { w: W, h: H } = data;
  const lookup = new Map(Object.keys(data.countries).map((n) => [n.toLowerCase(), n]));

  container.style.setProperty("--map-ratio", `${W} / ${H}`);
  container.textContent = "";
  const svg = el("svg", { viewBox: `0 0 ${W} ${H}`, role: "img", "aria-label": "World map. Solved groups are highlighted." }, container);
  const land = el("g", { class: "land" }, svg);
  const marks = el("g", { class: "marks" }, svg);

  const pathByName = {};
  for (const [name, c] of Object.entries(data.countries)) {
    pathByName[name] = el("path", { d: c.d, class: "country" }, land);
    pathByName[name].appendChild(el("title")).textContent = name;
  }

  let view = { x: 0, y: 0, w: W, h: H };
  let raf = 0;

  /** Where is this quiz item on the map? A country to light up, a pin, or nothing. */
  function resolve(label, groupName) {
    for (const key of [`${label}@${groupName}`, label]) {
      if (data.points[key]) return { type: "pin", label, ...data.points[key] };
      if (data.alias[key]) return { type: "country", label, name: data.alias[key] };
    }
    const name = lookup.get(label.toLowerCase());
    return name ? { type: "country", label, name } : null;
  }

  const unitsPerPx = (vw) => vw / (svg.clientWidth || 360);

  function setView(v) {
    view = v;
    svg.setAttribute("viewBox", `${v.x} ${v.y} ${v.w} ${v.h}`);
    const u = unitsPerPx(v.w);
    marks.querySelectorAll(".mark").forEach((m) => {
      m.setAttribute("transform", `translate(${m.dataset.x} ${m.dataset.y}) scale(${u})`);
    });
  }

  function targetView(items) {
    let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    for (const it of items) {
      const [bx0, by0, bx1, by1] = it.type === "country" ? data.countries[it.name].bbox : [it.x - 8, it.y - 8, it.x + 8, it.y + 8];
      x0 = Math.min(x0, bx0); y0 = Math.min(y0, by0); x1 = Math.max(x1, bx1); y1 = Math.max(y1, by1);
    }
    if (!isFinite(x0)) return { x: 0, y: 0, w: W, h: H };
    const ratio = W / H;
    let vw = Math.max((x1 - x0) * 1.7, (y1 - y0) * 1.7 * ratio, 260);
    vw = Math.min(vw, W);
    const vh = vw / ratio;
    const vx = Math.max(0, Math.min(W - vw, (x0 + x1) / 2 - vw / 2));
    const vy = Math.max(0, Math.min(H - vh, (y0 + y1) / 2 - vh / 2));
    return { x: vx, y: vy, w: vw, h: vh };
  }

  function animateTo(target, animate) {
    cancelAnimationFrame(raf);
    if (!animate || reducedMotion()) return setView(target);
    const from = view;
    const start = performance.now();
    const dur = 650;
    const step = (now) => {
      const t = Math.min(1, (now - start) / dur);
      const k = ease(t);
      setView({
        x: from.x + (target.x - from.x) * k,
        y: from.y + (target.y - from.y) * k,
        w: from.w + (target.w - from.w) * k,
        h: from.h + (target.h - from.h) * k,
      });
      if (t < 1) raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
  }

  /** Puts labels next to their marker without letting them cover each other (works in screen pixels). */
  function placeLabels(items, target) {
    const u = unitsPerPx(target.w);
    const th = 14;
    const rect = (x, y, w, h) => ({ x, y, w, h });
    const hit = (a, b) => a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
    const overlapArea = (a, b) => Math.max(0, Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x)) * Math.max(0, Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y));

    const pos = items.map((it) => ({ px: (it.mx - target.x) / u, py: (it.my - target.y) / u }));
    // Markers are obstacles for every label, so reserve their space first.
    const taken = items.flatMap((it, i) => (it.type === "pin" || it.small ? [rect(pos[i].px - 7, pos[i].py - 7, 14, 14)] : []));

    return items.map((it, i) => {
      const { px, py } = pos[i];
      const tw = it.label.length * 6.6 + 6;
      const isCountry = it.type === "country" && !it.small;
      const g = isCountry ? 0 : 9;
      const options = isCountry
        ? [[-tw / 2, -th / 2], [-tw / 2, th * 0.6], [-tw / 2, -th * 1.6], [-tw / 2, th * 1.7], [-tw / 2, -th * 2.6]]
        : [];
      if (!isCountry) {
        for (const extra of [0, th, th * 2]) {
          options.push([g, -th / 2 - extra], [-g - tw, -th / 2 - extra], [g, -th / 2 + extra], [-g - tw, -th / 2 + extra]);
        }
        options.push([-tw / 2, -th - 7], [-tw / 2, 9]);
      }
      let best = options[0];
      let bestScore = Infinity;
      for (const o of options) {
        const r = rect(px + o[0], py + o[1], tw, th);
        const score = taken.reduce((sum, t) => sum + overlapArea(r, t), 0);
        if (score < bestScore) { bestScore = score; best = o; }
        if (score === 0) break;
      }
      taken.push(rect(px + best[0], py + best[1], tw, th));
      return { dx: best[0] + tw / 2, dy: best[1] + th - 3 };
    });
  }

  /**
   * groups: [{ gi, name, items: [label, ...] }] in the order they were solved.
   * The last one is treated as "new" and gets a little pop animation.
   */
  function update(groups, { animate = true } = {}) {
    Object.values(pathByName).forEach((p) => { p.setAttribute("class", "country"); });
    marks.textContent = "";

    const items = [];
    groups.forEach((g, idx) => {
      for (const label of g.items) {
        const r = resolve(label, g.name);
        if (!r) continue;
        const isNew = idx === groups.length - 1;
        if (r.type === "country") {
          const c = data.countries[r.name];
          const p = pathByName[r.name];
          p.setAttribute("class", `country lit lit-${g.gi}${isNew ? " pop" : ""}`);
          land.appendChild(p); // draw lit countries on top so their outline is visible
          // Tiny countries (islands at this scale) also get a dot so they are easy to spot.
          const small = c.bbox[2] - c.bbox[0] < 14 && c.bbox[3] - c.bbox[1] < 14;
          items.push({ ...r, gi: g.gi, isNew, small, mx: c.c[0], my: c.c[1] });
        } else {
          items.push({ ...r, gi: g.gi, isNew, mx: r.x, my: r.y });
        }
      }
    });

    const target = targetView(items);
    const labels = placeLabels(items, target);
    const u = unitsPerPx(view.w);

    items.forEach((it, i) => {
      const m = el("g", { class: `mark g${it.gi}${it.isNew ? " pop" : ""}`, "data-x": it.mx, "data-y": it.my, transform: `translate(${it.mx} ${it.my}) scale(${u})` }, marks);
      m.appendChild(el("title")).textContent = it.label;
      if (it.type === "pin") m.appendChild((SHAPES[it.kind] || SHAPES.area)());
      else if (it.small) m.appendChild(SHAPES.micro());
      const t = el("text", { x: labels[i].dx, y: labels[i].dy, "text-anchor": "middle", class: it.type === "country" ? "clabel" : "plabel" }, m);
      t.textContent = it.label;
    });

    animateTo(target, animate);
  }

  return { update, get hasData() { return true; } };
}
